# Generated by Django 5.0 on 2023-12-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detectFruits',
            fields=[
                ('ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_excode', models.CharField(max_length=50)),
                ('ref_exname', models.CharField(default='fruits', max_length=50)),
                ('ref_exdate', models.IntegerField()),
                ('ref_quantity', models.IntegerField(default='1')),
            ],
        ),
    ]
